refresh_rate: 30 seconds
appenders:
  taxonomy:
    kind: file
    path: log/taxonomy.log
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} -{i} - {M} - {l}: {m}{n})}"
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} -{i} - {l}: {m}{n})}"
root:
  level: info
  appenders:
    - taxonomy
loggers:
  actix_web::middleware::logger:
    level: info
    appenders:
      - requests
    additive: false
